### ISSUE TITLE
Loop Printer Extension not working (macbook)

### ISSUE THREAD

**Issue by JVivie** [IceBear-Creative-Igloo/LoopPrinter#4]
Good day! 
maybe I am missing an important step but unfortunately I am not managing to get the loop printer extension to work on either chrome or edge. I am using a 2018 MacBook pro, Sonoma 14.4.1
I can download the extension on both browsers and do get to see the buttons (print current page / found a bug / request feature), but when clicking on "print current page" when in Loop nothing happens - no error is given.. The other 2 buttons do work. I have tried closing & opening the browsers as well as rebooting. Thanks for looking into this!

 - OS: MacOS
 - Browser Chrome, Edge
 - Version 124.0.6367.119 / 124.0.2478.80 respectively

**Comment by JVivie** [comment]
ps I tried with different page types including test pages with only text

**Comment by mattonik** [comment]
Hello,
thank you for your report.
Currently the plugin is set to work on a subset of domains (https://loop.microsoft.com/p/*)
Is there any chance you are accessing the notes through different URL @JVivie ?

**Comment by JVivie** [comment]
hi! thanks for ultra-speedy reply. I indeed use https://loop.microsoft.com/p/* (just double checked!)

**Comment by mattonik** [comment]
Ok, so that's one thing crossed, unfortunately the easiest one...
Can you check in DevTools (Cmd + Shift + I) to see if you get any errors there?

For obvious security and privacy reasons I don't collect any data from usage which makes the debugging a bit harder

**Comment by JVivie** [comment]
hi Mattonik! when I have devtools open the print page button works... funny way of doing it but thanks a lot for your help!!!
